# Generated by Django 4.1.5 on 2023-01-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='locality',
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
