# Generated by Django 4.1.5 on 2023-02-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
