# Generated by Django 4.1.5 on 2023-02-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_orders_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
