# Generated by Django 4.1.5 on 2023-02-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
