# Generated by Django 4.1.5 on 2023-02-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_orderplaced_payment_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
    ]
