# Generated by Django 4.1.5 on 2023-02-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
