# Generated by Django 4.1.5 on 2023-02-10 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_order_date_ordered_orderproduct_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
    ]
