# Generated by Django 4.1.5 on 2023-02-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
