# Generated by Django 5.1.5 on 2025-05-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mo', 'Monitors'), ('CA', 'Camera'), ('Ke', 'Keyboards'), ('Ms', 'Mouses'), ('He', 'Headsets'), ('Mp', 'Mousepads'), ('Jo', 'Joysticks'), ('Mi', 'Microphones'), ('Sp', 'Speekers')], max_length=2),
        ),
    ]
