# Generated by Django 5.1.5 on 2025-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_product_stock_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
